
#
# Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#
chr: 21
data_path: "/DLGWAS/data/"
data_identifier: "100k"
annotation_name: "gencode.v19.annotation.gtf"
features: ["gene", "transcript", "exon"] 
matrix_name: "snp_matrix.raw"
snplist_name: "snp_list.bim"
ignore_gene_map: False
separator: "\t"