chr: 1
data_path: "/home/dreidenbach/Desktop/gwas/hapgen2/data/"
data_identifier: "100k"
phenotype_experiement_name: "full_chr1_run"
prefilter: "exon"
interactive_cut: 0.2
mask_rate: 0.1
dosage_frac: 0.5
max_interaction_coeff: 2
phenotype_threshold: 50
noise_scalar: 1
heritability: 1
causal_snp_mode: "gene"
n_causal_snps: 100
causal_gene_cut: 0.05
max_gene_risk: 5
patient_chunk: 20000